Repository prabhus489/BiasCalculator-Pro, pull requests merged in 2022-05, with the labels that each got.

#20 Initial Stable code release
  PercentageInteger.py
  Percentage_Float.py
  README.md
  SimpleCalculator.py
  calc.png
  calc_small.png
  calculator.py
Labels: bug, enhancement, help wanted, good first issue

#30 Added a comment in Calculator.py
  calculator.py
  test_calculator.py
Labels: enhancement

#31 Added a comment in percentageinteger.py
  PercentageInteger.py
Labels: enhancement

#36 added division functionality
  division.py
Labels: good first issue

#37 added method for exponent functionality
  exponent.py
Labels: good first issue

#40 enhanced addition functionality
  Addition.py
  Subtraction.py
Labels: enhancement
